language: python  

python:
    - 3.7.1

cache: pip

install:
    - sudo locale-gen zh_CN.UTF-8
    - sudo locale-gen en_US.UTF-8
    - pip install --upgrade pip
    - pip install wheel
    - pip install -r requirements.txt

script:
    - python setup.py bdist_wheel

before_deploy:
    - cd dist/

deploy:
    provider: releases
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file: 
        - "$TRAVIS_BUILD_DIR/dist/*"
    skip_cleanup: true
    on:
        tags: true
